### ISSUE TITLE
Update for 14-1

### ISSUE THREAD

**Issue by Arnaud-Trouche** [The-CJ/discourse-flarum#1]
Hi,

Thank you very much for this great script that enabled me to import ~800 topics from discourse to flarum.

To use with latest version, here the changes I made in the yml, it may benefit other people.
(In my case, I had also to comment with # 'parent_category' in categories/tags and 'last_post_user_id' in topics/discussions.

````
#yaml-migration-config
---
authentification:
  old-database:
    host: TBC
    name: TBC
    user: TBC
    password: TBC
  new-database:
    host: TBC
    name: TBC
    user: TBC
    password: TBC

steps:
- action: COPY
  enabled: true
  old-table: users
  new-table: users
  columns:
    id: id
    username: username
    name: email
    password_hash: password
    created_at: joined_at
    last_seen_at: last_seen_at
- action: RUN_COMMAND
  enabled: true
  command: UPDATE users SET is_email_confirmed=1
    
- action: COPY
  enabled: true
  old-table: categories
  new-table: tags
  columns:
    id: id
    name: name
    color: color
    position: position
    slug: slug
    description: description
    parent_category_id: parent_id
    
- action: COPY
  enabled: true
  old-table: topics
  new-table: discussions
  columns:
    id: id
    title: title
    posts_count++: comment_count
    participant_count: participant_count
    created_at: created_at
    user_id: user_id
    updated_at: last_posted_at
    last_post_user_id: last_posted_user_id
    slug: slug
- action: RUN_COMMAND
  enabled: true
  command: DELETE FROM discussions WHERE title='Backup completed successfully'
  
- action: COPY
  enabled: true
  old-table: posts
  new-table: posts
  columns:
    id: id
    user_id: user_id
    topic_id: discussion_id
    cooked*: content
    created_at: created_at
    updated_at: edited_at
- action: RUN_COMMAND
  enabled: true
  command: UPDATE posts SET type='comment'
- action: RUN_COMMAND
  enabled: true
  command: DELETE FROM posts WHERE user_id='-1'

- action: FIRST_AND_LAST
  enabled: true
  table: discussions
  from-table: posts
  start_post_id: last_post_id

- action: COPY
  enabled: true
  old-table: topics
  new-table: discussion_tag
  columns:
    id: discussion_id
    category_id: tag_id

- action: RUN_COMMAND
  enabled: false
  command: DELETE FROM users WHERE password='NULL'
````
